### ISSUE TITLE
Get all statuses of a "zaak"

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/mijngemeente-gateway#11]
As a **user** I want to be able get all statuses of a "zaak". This forwards the request to relevant [OpenZaak endpoint](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/zaken-api/1.1.0/src/openapi.yaml#/statussen/status_list).

**Out of scope**
- Unit tests and logging

**Depends on:**
- #2 Basic ExpressJS server

**Acceptance Criterion**:
- [x] Mimic the functionality of the [FE gateway](https://dev.azure.com/mijndenhaag/mdh/_git/lopende_zaken?path=%2Fgateway) [[code]](https://dev.azure.com/mijndenhaag/mdh/_git/lopende_zaken?path=%2Fgateway%2Fsrc%2Fmain%2Fjava%2Fnl%2Fdenhaag%2Fpwapoc%2Fgateway%2FGatewayApplication.java&version=GBmaster&line=203&lineEnd=217&lineStartColumn=1&lineEndColumn=3&lineStyle=plain&_a=contents).
- [x] Endpoint should be a 1:1 mapping with the OpenZaak endpoint
- [x] Backend OpenZaak url should not be hardcoded (environment)

**Comment by bddjong** [comment]
Gateway is no longer under development. The decision has been made to use mockdata in the PWA.
