### ISSUE TITLE
Establishing testing strategy

### ISSUE THREAD

**Issue by bddjong** [Gemeente-DenHaag/mijngemeente-gateway#33]
**A testing strategy should be defined for the gateway**

## Details
Currently, no decisions have been made about testing. When the gateway grows in functionality, it will become harder to test and ascertain whether or not it continues to function in-between changes. We should decide how we test (what kind of tests, which frameworks and a targeted coverage) the Gateway to ensure it remains functional after a change has been made and to ensure a newly added piece of functionality works as expected.

If the functionality that needs to be tested at the moment we start working on this story is still limited, apply the testing strategy to all current code where it's deemed necessary. If the amount of untested code is significant, a separate story should be made to create the tests.

## Acceptance criteria
- [ ] Desired types of tests are determined and discussed (smoke, functional, unit)
- [ ] Suggestions or decisions for frameworks are determined
- [ ] Tests are added to the codebase if in scope
- [ ] Testing guidelines are documented in README.md

**Comment by bddjong** [comment]
Possibly obsolete if a reference architecture will be developed. The scope of our gateway would in that case be reduced to purely serving the PWA, instead of being reusable and scalable.

**Comment by mjcarsjens** [comment]
@bddjong This issue can indeed be removed. For now we will simply work with our very low-level gateway, adding any functionality which we do not necessarily need for our PWA to work is simply said a waste of time and resources.

**Comment by bddjong** [comment]
No longer relevant as the gateway we're currently developing will not be the final reusable gateway.
