### ISSUE TITLE
Establishing logging strategy

### ISSUE THREAD

**Issue by bddjong** [Gemeente-DenHaag/mijngemeente-gateway#34]
**A logging strategy should be defined for the gateway**

## Details
We should implement a robust logging system to increase observability of the application, and assist with tracking down bugs or other issues. At the very least, we should be able to log requests made to the gateway. It could be beneficial to research best practices for logging. It might be desired to have different logging levels, which depend on whether or not the application is running in production or in a development environment.

As logs can sometimes contain highly sensitive and personal data we should have a clear view on what information can and cannot be logged. Furthermore, a strategy on how to access the logs (and who has access to them) should be made.

## Acceptance criteria
- [ ] Suggestions or decisions for logging strategy and possible framework(s) are made
- [ ] Currently existing requests are logged where deemed necessary
- [ ] A strategy on what data can and cannot be logged is made
- [ ] Logging information is documented in README.md

**Comment by bddjong** [comment]
Possibly obsolete if a reference architecture will be developed. The scope of **our** gateway would in that case be reduced to purely serving the PWA, instead of being reusable and scalable.

**Comment by mjcarsjens** [comment]
@bddjong This issue can indeed be removed. For now we will simply work with our very low-level gateway, adding any functionality which we do not necessarily need for our PWA to work is simply said a waste of time and resources.
