### ISSUE TITLE
Continuous Deployment of Gateway

### ISSUE THREAD

**Issue by bddjong** [Gemeente-DenHaag/mijngemeente-gateway#35]
**The gateway should be deployed from its master branch and development branch**

## Details
Currently, no CD has been implemented. For this story we will create a production and staging environment running the gateway that the respective PWA environments can talk with. These environments should be created and updated automatically from the development and the master branch respectively.

## Acceptance criteria
- [ ] A server is available where de gateway can be deployed
- [ ] Gateway deploys from development branch to a staging environment that's accessible on the web through HTTPS
- [ ] Gateway deploys from master branch to a prod environment that's accessible on the web through HTTPS

**Gateway environment variables for:**
- [ ] OpenZaak URL
- [ ] OpenZaak client_id
- [ ] OpenZaak secret

**Comment by bddjong** [comment]
Possibly obsolete if a reference architecture will be developed. The scope of our gateway would in that case be reduced to purely serving the PWA, instead of being reusable and scalable.

**Comment by mjcarsjens** [comment]
@bddjong This issue is still relevant, as we still want a pre-prod and prod gateway environment running on a server somewhere for our PWA to communicate with.

**Comment by ogjtech** [comment]
I would suggest adding any tests and linters being run before deployment to the acceptance criteria.

**Comment by Test-Automation-Engineer** [comment]
@bddjong If I can be of any assistance, let me know
